name: visible_gw_events
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - streamlit=1.1.0
  - numpy
  - scipy
  - matplotlib
  - corner
  - h5py
  - ipython
  - pip
  - pandas
  - tqdm
  - pip:
    - simple-parsing
    - firebase-admin
    - plotly