name: visible_gw_events
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - streamlit
  - numpy
  - scipy
  - matplotlib
  - scikit-learn
  - corner
  - h5py
  - jupyterlab
  - ipython
  - pip
  - pandas
  - tqdm
  - ligo.skymap
  - bilby
  - astropy
  - gwosc
  - gwpy
  - pip:
    - jupyterlab-unfold
    - -e .  # install package in development mode
    - simple-parsing
    - firebase-admin
    - tables
    - plotly
    - jupyterlab>=3
    - notebook>=5.3
    - ipywidgets>=7.6
    - jupyter-dash